1. SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE SALARY NOT BETWEEN 10000 AND 15000 AND DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 100
2. SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) FROM hr_db.employees WHERE HIRE_DATE LIKE '%1987%'
3. SELECT FIRST_NAME FROM employees WHERE FIRST_NAME LIKE '%b%' OR FIRST_NAME LIKE '%c%'
4. SELECT LAST_NAME, JOB_ID, SALARY FROM hr_db.employees WHERE (JOB_ID = 'IT_PROG' OR JOB_ID = 'SH_CLERK') AND (SALARY != 4500 OR SALARY != 10000 OR SALARY != 15000);
5. SELECT * FROM employees WHERE LAST_NAME LIKE '%BLAKE%' OR LAST_NAME LIKE '%SCOTT%' OR LAST_NAME LIKE '%KING%' OR LAST_NAME LIKE '%FORD%'